version: '3'
services:
  postgres:
    image: postgres:14
    container_name: legend-postgres
    environment:
      POSTGRES_USER: legend
      POSTGRES_PASSWORD: legend123
      POSTGRES_DB: legenddb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
